// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Nicola Mustone
// Generated by `npm run db:types`. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          at: string
          detail: Json | null
          id: number
          target: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          at?: string
          detail?: Json | null
          id?: number
          target?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          at?: string
          detail?: Json | null
          id?: number
          target?: string | null
        }
        Relationships: []
      }
      byline_grants: {
        Row: {
          granted_at: string
          note: string | null
          owner_id: string
        }
        Insert: {
          granted_at?: string
          note?: string | null
          owner_id: string
        }
        Update: {
          granted_at?: string
          note?: string | null
          owner_id?: string
        }
        Relationships: []
      }
      campaigns: {
        Row: {
          created_at: string
          data: Json
          id: string
          name: string | null
          owner_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          data: Json
          id?: string
          name?: string | null
          owner_id?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          data?: Json
          id?: string
          name?: string | null
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      capabilities: {
        Row: {
          capability: string
          description: string
        }
        Insert: {
          capability: string
          description: string
        }
        Update: {
          capability?: string
          description?: string
        }
        Relationships: []
      }
      capability_denials: {
        Row: {
          capability: string
          denied_at: string
          denied_by: string | null
          owner_id: string
          reason: string | null
        }
        Insert: {
          capability: string
          denied_at?: string
          denied_by?: string | null
          owner_id: string
          reason?: string | null
        }
        Update: {
          capability?: string
          denied_at?: string
          denied_by?: string | null
          owner_id?: string
          reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "capability_denials_capability_fkey"
            columns: ["capability"]
            isOneToOne: false
            referencedRelation: "capabilities"
            referencedColumns: ["capability"]
          },
        ]
      }
      creatures: {
        Row: {
          data: Json
          id: string
          name: string
          owner_id: string
          updated_at: string
        }
        Insert: {
          data: Json
          id?: string
          name: string
          owner_id?: string
          updated_at?: string
        }
        Update: {
          data?: Json
          id?: string
          name?: string
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      effects: {
        Row: {
          created_at: string
          data: Json | null
          id: string
          name: string | null
          owner_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          data?: Json | null
          id?: string
          name?: string | null
          owner_id?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          data?: Json | null
          id?: string
          name?: string | null
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      encounter_revisions: {
        Row: {
          checkpoint: boolean
          created_at: string
          encounter_id: string
          owner_id: string
          revision: number
          state: Json
        }
        Insert: {
          checkpoint?: boolean
          created_at?: string
          encounter_id: string
          owner_id: string
          revision: number
          state: Json
        }
        Update: {
          checkpoint?: boolean
          created_at?: string
          encounter_id?: string
          owner_id?: string
          revision?: number
          state?: Json
        }
        Relationships: [
          {
            foreignKeyName: "encounter_revisions_encounter_id_fkey"
            columns: ["encounter_id"]
            isOneToOne: false
            referencedRelation: "encounters"
            referencedColumns: ["id"]
          },
        ]
      }
      encounter_writer_leases: {
        Row: {
          encounter_id: string
          expires_at: string
          owner_id: string
          updated_at: string
          writer_id: string
        }
        Insert: {
          encounter_id: string
          expires_at: string
          owner_id: string
          updated_at?: string
          writer_id: string
        }
        Update: {
          encounter_id?: string
          expires_at?: string
          owner_id?: string
          updated_at?: string
          writer_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "encounter_writer_leases_encounter_id_fkey"
            columns: ["encounter_id"]
            isOneToOne: true
            referencedRelation: "encounters"
            referencedColumns: ["id"]
          },
        ]
      }
      encounters: {
        Row: {
          campaign_id: string | null
          id: string
          kind: string
          name: string | null
          owner_id: string
          player_code: string | null
          revision: number
          state: Json
          status: string
          updated_at: string
        }
        Insert: {
          campaign_id?: string | null
          id?: string
          kind?: string
          name?: string | null
          owner_id?: string
          player_code?: string | null
          revision?: number
          state: Json
          status?: string
          updated_at?: string
        }
        Update: {
          campaign_id?: string | null
          id?: string
          kind?: string
          name?: string | null
          owner_id?: string
          player_code?: string | null
          revision?: number
          state?: Json
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      live_view_sessions: {
        Row: {
          capability_hash: string
          code: string
          encounter_id: string
          generation: number
          owner_id: string
          rotated_at: string
        }
        Insert: {
          capability_hash: string
          code: string
          encounter_id: string
          generation?: number
          owner_id: string
          rotated_at?: string
        }
        Update: {
          capability_hash?: string
          code?: string
          encounter_id?: string
          generation?: number
          owner_id?: string
          rotated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "live_view_sessions_encounter_id_fkey"
            columns: ["encounter_id"]
            isOneToOne: true
            referencedRelation: "encounters"
            referencedColumns: ["id"]
          },
        ]
      }
      players: {
        Row: {
          data: Json
          id: string
          name: string | null
          owner_id: string
          updated_at: string
        }
        Insert: {
          data: Json
          id?: string
          name?: string | null
          owner_id?: string
          updated_at?: string
        }
        Update: {
          data?: Json
          id?: string
          name?: string | null
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      role_capabilities: {
        Row: {
          capability: string
          role: string
        }
        Insert: {
          capability: string
          role: string
        }
        Update: {
          capability?: string
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "role_capabilities_capability_fkey"
            columns: ["capability"]
            isOneToOne: false
            referencedRelation: "capabilities"
            referencedColumns: ["capability"]
          },
        ]
      }
      role_inherits: {
        Row: {
          inherits: string
          role: string
        }
        Insert: {
          inherits: string
          role: string
        }
        Update: {
          inherits?: string
          role?: string
        }
        Relationships: []
      }
      share_reports: {
        Row: {
          code: string
          created_at: string
          id: string
          message: string | null
          reason: string
          reply_to: string | null
          reporter_id: string | null
          resolution: string | null
          resolved_at: string | null
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          message?: string | null
          reason: string
          reply_to?: string | null
          reporter_id?: string | null
          resolution?: string | null
          resolved_at?: string | null
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          message?: string | null
          reason?: string
          reply_to?: string | null
          reporter_id?: string | null
          resolution?: string | null
          resolved_at?: string | null
        }
        Relationships: []
      }
      share_tombstones: {
        Row: {
          code: string
          taken_down_at: string
        }
        Insert: {
          code: string
          taken_down_at?: string
        }
        Update: {
          code?: string
          taken_down_at?: string
        }
        Relationships: []
      }
      shares: {
        Row: {
          code: string
          created_at: string
          data: Json
          kind: string
          owner_id: string
        }
        Insert: {
          code: string
          created_at?: string
          data: Json
          kind: string
          owner_id?: string
        }
        Update: {
          code?: string
          created_at?: string
          data?: Json
          kind?: string
          owner_id?: string
        }
        Relationships: []
      }
      spells: {
        Row: {
          created_at: string
          data: Json | null
          id: string
          name: string | null
          owner_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          data?: Json | null
          id?: string
          name?: string | null
          owner_id?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          data?: Json | null
          id?: string
          name?: string | null
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      takedown_notices: {
        Row: {
          code: string
          created_at: string
          id: string
          to_address: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          to_address: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          to_address?: string
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          granted_at: string
          granted_by: string | null
          note: string | null
          owner_id: string
          role: string
        }
        Insert: {
          granted_at?: string
          granted_by?: string | null
          note?: string | null
          owner_id: string
          role: string
        }
        Update: {
          granted_at?: string
          granted_by?: string | null
          note?: string | null
          owner_id?: string
          role?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      account_libraries: {
        Args: never
        Returns: {
          campaigns: number
          creatures: number
          id: string
          published: number
        }[]
      }
      account_made: {
        Args: { limit_to?: number; who: string }
        Returns: {
          at: string
          code: string
          edition: string
          imported: boolean
          kind: string
          license: string
          name: string
          source: string
        }[]
      }
      account_overview: {
        Args: { who: string }
        Returns: {
          campaigns: number
          creatures: number
          player_code: string
          published: number
          saved_fights: number
        }[]
      }
      accounts: {
        Args: { limit_to?: number }
        Returns: {
          created_at: string
          denials: string[]
          display_name: string
          email: string
          full_name: string
          id: string
          last_sign_in_at: string
          providers: string[]
          roles: string[]
          signed_in_with: string
        }[]
      }
      answer_reports: {
        Args: { decision: string; want: string }
        Returns: number
      }
      audit_recent: {
        Args: { limit_to?: number }
        Returns: {
          action: string
          actor_id: string | null
          at: string
          detail: Json | null
          id: number
          target: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "audit_log"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      capabilities_of: {
        Args: { who: string }
        Returns: {
          capability: string
          denied: boolean
          via: string
        }[]
      }
      claim_encounter_writer: {
        Args: { want_encounter: string; want_writer: string }
        Returns: Json
      }
      delete_account: { Args: never; Returns: undefined }
      deny_capability: {
        Args: { cap: string; who: string; why?: string }
        Returns: boolean
      }
      grant_role: {
        Args: { what: string; who: string; why?: string }
        Returns: boolean
      }
      live_view_topic_active: { Args: { want_topic: string }; Returns: boolean }
      live_view_topic_owned: { Args: { want_topic: string }; Returns: boolean }
      may: { Args: { cap: string }; Returns: boolean }
      may_publish_more: { Args: never; Returns: boolean }
      may_use_reserved_byline: { Args: never; Returns: boolean }
      my_capabilities: { Args: never; Returns: string[] }
      note_action: {
        Args: { extra?: Json; what: string; which: string }
        Returns: undefined
      }
      report_share: {
        Args: { note?: string; reply_to?: string; want: string; why: string }
        Returns: undefined
      }
      reported_share: {
        Args: { want: string }
        Returns: {
          created_at: string
          data: Json
          kind: string
          owned: boolean
        }[]
      }
      reports_for: {
        Args: { want: string }
        Returns: {
          created_at: string
          id: string
          message: string
          reason: string
          reply_to: string
          resolution: string
          resolved_at: string
        }[]
      }
      reports_open: { Args: never; Returns: number }
      reports_queue: {
        Args: { limit_to?: number }
        Returns: {
          code: string
          first_at: string
          last_at: string
          reasons: string[]
          reports: number
          still_open: number
          still_published: boolean
        }[]
      }
      restore_capability: {
        Args: { cap: string; who: string }
        Returns: boolean
      }
      revoke_role: { Args: { what: string; who: string }; Returns: boolean }
      roles_of: { Args: { who: string }; Returns: string[] }
      save_encounter_revision: {
        Args: {
          expected_revision: number
          want_encounter: string
          want_owner: string
          want_state: Json
          want_updated_at: string
          want_writer: string
        }
        Returns: Json
      }
      share: { Args: { want: string }; Returns: Json }
      start_live_view: {
        Args: {
          want_capability_hash: string
          want_code: string
          want_encounter: string
        }
        Returns: number
      }
      stop_all_live_views: { Args: never; Returns: boolean }
      stop_live_view: {
        Args: { want_capability_hash: string }
        Returns: boolean
      }
      takeover_encounter_writer: {
        Args: { want_encounter: string; want_writer: string }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
