-- SPDX-License-Identifier: AGPL-3.0-or-later
-- Copyright (C) 2026 Nicola Mustone
-- Canonical copy of the reviewed admin role authority.

-- Roles and capabilities for admin.openfray.app. The tracked migration order applies this
-- after the core console tables and before publishing and moderation authority.
--
-- Nothing in the console reads any of this. Every check happens inside a security
-- definer function that answers for auth.uid(), so the dashboard holds no
-- service-role key and a signed-in Game Master calling one by hand gets nothing.
--
-- ── Read this before adding a function here ─────────────────────────────────────
-- A security definer function runs as its owner and bypasses row-level security
-- completely. Three rules keep that from becoming a hole:
--
--   1. `set search_path = public` on every one. Without it, a caller who can create
--      objects in an earlier schema decides what `user_roles` means.
--   2. `revoke execute ... from public` on every one. PostgreSQL grants EXECUTE to
--      PUBLIC on a new function by default, and Supabase's `anon` inherits PUBLIC.
--      Granting to `authenticated` does not undo that; only the revoke does.
--   3. Touch only the tables named in the function's own comment. A definer function
--      that reads `encounters` or `shares` reads every account's rows at once.

-- ── Why not user_metadata ───────────────────────────────────────────────────────
-- The account default license lives in user_metadata, and the app validates it on
-- read because a user can write their own metadata with the anon key. A role written
-- there would be self-granted. Roles live in a table with no policies, and only the
-- functions below read it.

-- ── Roles ───────────────────────────────────────────────────────────────────────
-- One row per role held, so an account can hold several. `role` is text with a check
-- rather than an enum: adding a role is an insert here and a new constraint, never an
-- ALTER TYPE. `granted_by` records who did it, because a role change is the most
-- consequential write in this schema.

create table if not exists user_roles (
  owner_id uuid not null references auth.users on delete cascade,
  role text not null,
  note text,
  granted_by uuid references auth.users on delete set null,
  granted_at timestamptz not null default now(),
  primary key (owner_id, role),
  constraint role_known check (role in ('gm', 'admin', 'editor', 'moderator', 'creator'))
);
alter table user_roles enable row level security;
-- No policies at all, and the grants revoked explicitly. RLS with no policy already
-- denies; the revoke means a policy added by mistake later still finds no privilege.
revoke all on table user_roles from anon, authenticated;

-- ── Capabilities ────────────────────────────────────────────────────────────────
-- Every gate in the dashboard asks for a capability, never for a role. A new role is
-- then rows in the mapping and nothing else: no function is edited, and no screen
-- learns a fourth name. That is what makes "creator" cheap to define later.
--
-- The catalog exists so the set is knowable. A capability the catalog does not list is
-- false for everybody, admin included, so a typo at a call site denies instead of
-- granting. It also gives a grant screen something to enumerate.

create table if not exists capabilities (
  capability text primary key,
  description text not null
);
alter table capabilities enable row level security;
revoke all on table capabilities from anon, authenticated;

insert into capabilities (capability, description) values
  ('create.creature', 'Write a custom creature'),
  ('create.spell', 'Write a custom spell'),
  ('create.campaign', 'Keep a campaign'),
  ('create.preset', 'Keep an effect preset'),
  ('create.encounter', 'Save an encounter'),
  ('create.character', 'Keep a player character'),
  ('share.encounter', 'Publish an encounter to a link'),
  ('share.creature', 'Publish a creature to a link'),
  ('reports.read', 'See the queue of reports filed against published links'),
  ('reports.resolve', 'Answer a report: dismiss it, or take the page down'),
  ('shares.read', 'Look up a published link by code and read what a reader sees'),
  ('shares.takedown', 'Delete a published link'),
  ('jobs.read', 'See whether the nightly sweep and backup ran'),
  ('audit.read', 'Read the log of what was done and by whom'),
  ('content.write', 'Edit stat blocks, spells, and published encounters'),
  ('roles.grant', 'Grant and withdraw a role')
on conflict (capability) do update set description = excluded.description;

-- `content.write` has nothing to act on yet. The compendium ships as static JSON in
-- console/public/compendium/, generated by the compendium repo and never edited in the
-- app, so an editor's work needs either a table for that content or a pipeline into
-- that repo. The capability is named now so the role means something when it exists.

create table if not exists role_capabilities (
  role text not null,
  capability text not null references capabilities on delete cascade,
  primary key (role, capability),
  constraint capability_role_known check (
    role in ('gm', 'admin', 'editor', 'moderator', 'creator')
  )
);
alter table role_capabilities enable row level security;
revoke all on table role_capabilities from anon, authenticated;

-- What each role may do. `admin` holds no rows here: it is answered by may() directly,
-- so a capability invented next year needs no migration to reach the maintainer.
-- `jobs.read`, `audit.read` and `roles.grant` have no rows, which leaves them
-- admin-only.
-- Everybody who signs up is a `gm`, so what it holds is what an ordinary account may do.
-- The name is what the account is rather than what it was given: a `player` app or a
-- `creator` tier would be another kind of account beside it, not another grant on top.
insert into role_capabilities (role, capability) values
  ('gm', 'create.creature'),
  ('gm', 'create.spell'),
  ('gm', 'create.campaign'),
  ('gm', 'create.preset'),
  ('gm', 'create.encounter'),
  ('gm', 'create.character'),
  ('gm', 'share.encounter'),
  ('gm', 'share.creature')
on conflict do nothing;

-- **Only the two share capabilities are enforced today.** The `shares` policy asks may() at
-- publish time; nothing asks about create.*, so denying one changes nothing yet.
--
-- They are here anyway, and it is not decoration. A capability has to exist before a role can
-- be composed out of it, and the grants have to exist before anything checks them: the day an
-- RLS policy on `creatures` asks may('create.creature'), every account already holds it, and
-- the alternative is a migration that locks everybody out of their own library for as long as
-- it takes to notice. A campaign-editor role holding create.campaign and nothing else is then
-- rows in this table.

-- What each role may do, admin included. It used to be answered by a short-circuit in may()
-- and is answered from this table now, like everybody else. The three below are what no other
-- role reaches; the rest arrive by inheritance from moderator, editor and gm.
--
-- The cost of retiring that short-circuit is that a capability invented next year does not
-- reach an admin until a row here says so. Worth paying: it is visible in a table rather than
-- hidden in a function, and capabilities_of() shows exactly what somebody holds and why.
insert into role_capabilities (role, capability) values
  ('admin', 'jobs.read'),
  ('admin', 'audit.read'),
  ('admin', 'roles.grant'),
  ('moderator', 'reports.read'),
  ('moderator', 'reports.resolve'),
  ('moderator', 'shares.read'),
  ('moderator', 'shares.takedown'),
  ('editor', 'content.write'),
  ('editor', 'shares.read')
on conflict do nothing;

-- Answering a report mails its reporter, and that mail is sent by a database webhook rather
-- than by anybody holding a capability. There is no mail.read or mail.reply any more: the
-- dashboard reads no mailbox, and the moderation migration removes them from a project that has them.

-- ── Taking one thing away from one account ──────────────────────────────────────
-- A role says what an account is, and every `gm` holds the same capabilities, so revoking
-- something from one person cannot be done by editing the role. This is where that goes.
--
-- It is the whole point of the exercise: an account that publishes something it should not
-- can be stopped from publishing without being deleted, and without stopping everybody else.
-- A denial beats a grant, including an admin's, because an admin denying themselves a
-- capability meant it.

create table if not exists capability_denials (
  owner_id uuid not null references auth.users on delete cascade,
  capability text not null references capabilities on delete cascade,
  reason text,
  denied_by uuid references auth.users on delete set null,
  denied_at timestamptz not null default now(),
  primary key (owner_id, capability)
);
alter table capability_denials enable row level security;
revoke all on table capability_denials from anon, authenticated;

-- `creator` holds no capabilities. Granting it today does nothing, which is the point:
-- the role can exist before anybody decides what it may do.

-- ── The audit log ───────────────────────────────────────────────────────────────
-- Append-only. Every consequential action writes one row from inside the function that
-- performs it, so an action and its record cannot come apart. Nothing may update or
-- delete a row here, including an admin: no function offers it, and the grants below
-- leave no direct privilege.
--
-- A takedown deletes the published row outright, so this log is the only place that
-- remembers it happened. `target` is the code or the id, kept as text because the row
-- it names is often gone by the time anybody reads this.

create table if not exists audit_log (
  id bigserial primary key,
  actor_id uuid references auth.users on delete set null,
  action text not null,
  target text,
  detail jsonb,
  at timestamptz not null default now()
);
alter table audit_log enable row level security;
revoke all on table audit_log from anon, authenticated;

create index if not exists audit_log_recent on audit_log (at desc);

/** One line in the log, written by the function doing the work. */
create or replace function note_action(what text, which text, extra jsonb default null)
  returns void
  language sql security definer set search_path = public
  as $$
    insert into audit_log (actor_id, action, target, detail)
    values (auth.uid(), what, which, extra)
  $$;
-- Not callable from a client at all: only the definer functions below invoke it, and
-- they run as the owner. A client that could write here could forge a record.
revoke execute on function note_action(text, text, jsonb) from public;

-- ── What a role includes ────────────────────────────────────────────────────────
-- One relationship in this list is a real "includes": every member of staff is also an
-- ordinary account with a library of their own. Editors and moderators inherit `gm`, and
-- admin inherits both of them, so one role per person covers the ordinary case.
--
-- Declared as edges rather than as a rank, because the roles are not in a line. An editor
-- rewrites stat blocks; a moderator reads reporters' addresses and deletes pages. Neither
-- contains the other, and any ordering that put one above the other would hand somebody a job
-- they were not given. A graph says admin includes both without claiming either outranks the
-- other, and a `player` or a `creator` can hang off `gm` later without joining a queue.
--
-- This is also what retired the admin short-circuit. may() used to answer true for an admin
-- without consulting anything, which is a hierarchy nobody declared and one that hid a
-- missing role: an admin with no `gm` row looked fine until the day the admin role went.

create table if not exists role_inherits (
  role text not null,
  inherits text not null,
  primary key (role, inherits),
  constraint inherits_known check (
    role in ('gm', 'admin', 'editor', 'moderator', 'creator')
    and inherits in ('gm', 'admin', 'editor', 'moderator', 'creator')
  ),
  -- A role inheriting itself is the shortest cycle, and the only one worth a constraint. The
  -- walk below stops on longer ones by tracking where it has been.
  constraint inherits_not_itself check (role <> inherits)
);
alter table role_inherits enable row level security;
revoke all on table role_inherits from anon, authenticated;

insert into role_inherits (role, inherits) values
  ('editor', 'gm'),
  ('moderator', 'gm'),
  ('creator', 'gm'),
  ('admin', 'moderator'),
  ('admin', 'editor')
on conflict do nothing;

/**
 * Every role an account holds, and everything those roles include, however deep.
 *
 * `cycle` is what makes a graph safe to walk: two roles inheriting each other would otherwise
 * recurse until the planner gives up, and a constraint cannot see a loop longer than one hop.
 */
create or replace function roles_of(who uuid) returns setof text
  language sql security definer set search_path = public stable
  as $$
    with recursive held as (
      select role from user_roles where owner_id = who
      union
      select i.inherits
      from held h
      join role_inherits i on i.role = h.role
    )
    select role from held
  $$;
revoke execute on function roles_of(uuid) from public;

-- ── The one gate ────────────────────────────────────────────────────────────────
-- Two conditions, in order: the capability is one the catalog defines, and the account
-- either is an admin or holds a role mapped to it.

create or replace function may(cap text) returns boolean
  language sql security definer set search_path = public stable
  as $$
    select exists (select 1 from capabilities where capability = cap)
      and not exists (
        select 1 from capability_denials
        where owner_id = auth.uid() and capability = cap
      )
      and exists (
        select 1
        from roles_of(auth.uid()) r
        join role_capabilities c on c.role = r
        where c.capability = cap
      )
  $$;
revoke execute on function may(text) from public;
grant execute on function may(text) to authenticated;

-- What the signed-in account may do, for a dashboard deciding which screens to draw.
-- A convenience, never a gate: every screen's data comes from a function that checks
-- may() again on the server side. An admin gets the whole catalog.
/**
 * What one account may do, and where each answer came from.
 *
 * `via` is the role that grants it, which is what makes several roles legible on a screen:
 * a reader seeing content.write beside "editor" does not have to hold the mapping in their
 * head. A denial keeps its row and is marked rather than dropped, because an exception that
 * disappears looks like something that was never granted.
 *
 * Answers about somebody else, so it is gated: only an account that hands out roles may ask.
 * my_capabilities() above asks about the caller and needs no such gate.
 */
create or replace function capabilities_of(who uuid)
  returns table (capability text, via text, denied boolean)
  language sql security definer set search_path = public stable
  as $$
    select c.capability,
           string_agg(distinct r, ', ' order by r) as via,
           exists (
             select 1 from capability_denials d
             where d.owner_id = who and d.capability = c.capability
           ) as denied
    from roles_of(who) r
    join role_capabilities c on c.role = r
    where who = auth.uid() or (select may('roles.grant'))
    group by c.capability
    order by c.capability
  $$;
revoke execute on function capabilities_of(uuid) from public;
grant execute on function capabilities_of(uuid) to authenticated;

create or replace function my_capabilities() returns setof text
  language sql security definer set search_path = public stable
  as $$ select capability from capabilities_of(auth.uid()) where not denied $$;
revoke execute on function my_capabilities() from public;
grant execute on function my_capabilities() to authenticated;



-- ── Granting ────────────────────────────────────────────────────────────────────
-- Gated on roles.grant, which only admin holds. The grantor is recorded from
-- auth.uid() rather than passed in, so a caller cannot attribute their own grant to
-- somebody else.

create or replace function grant_role(who uuid, what text, why text default null)
  returns boolean
  language plpgsql security definer set search_path = public
  as $$
  begin
    if not (select may('roles.grant')) then return false; end if;
    insert into user_roles (owner_id, role, note, granted_by)
    values (who, what, why, auth.uid())
    on conflict (owner_id, role) do update set note = excluded.note;
    perform note_action('role.grant', who::text, jsonb_build_object('role', what, 'note', why));
    return true;
  end
  $$;
revoke execute on function grant_role(uuid, text, text) from public;
grant execute on function grant_role(uuid, text, text) to authenticated;

create or replace function revoke_role(who uuid, what text) returns boolean
  language plpgsql security definer set search_path = public
  as $$
  declare gone integer;
  begin
    if not (select may('roles.grant')) then return false; end if;
    -- The last admin cannot be removed, including by themselves. A project with no
    -- admin has no way back except the SQL editor.
    --
    -- The lock is the whole point of taking it: two admins revoking each other at the
    -- same moment would both count two, both delete one, and leave none. Serialised on
    -- an arbitrary key shared by every caller of this branch.
    if what = 'admin' then
      perform pg_advisory_xact_lock(hashtext('user_roles.admin'));
      if (select count(*) from user_roles where role = 'admin') <= 1 then
        return false;
      end if;
    end if;
    delete from user_roles where owner_id = who and role = what;
    get diagnostics gone = row_count;
    if gone > 0 then
      perform note_action('role.revoke', who::text, jsonb_build_object('role', what));
    end if;
    return gone > 0;
  end
  $$;
revoke execute on function revoke_role(uuid, text) from public;
grant execute on function revoke_role(uuid, text) to authenticated;

-- ── Reading the log ─────────────────────────────────────────────────────────────
create or replace function audit_recent(limit_to integer default 100)
  returns setof audit_log
  language sql security definer set search_path = public stable
  as $$
    select * from audit_log
    where (select may('audit.read'))
    order by at desc
    limit least(coalesce(limit_to, 100), 500)
  $$;
revoke execute on function audit_recent(integer) from public;
grant execute on function audit_recent(integer) to authenticated;

-- Taking one capability from one account, and giving it back. Gated on roles.grant, so the
-- same person who hands out roles is the one who can restrict an account.

create or replace function deny_capability(who uuid, cap text, why text default null)
  returns boolean
  language plpgsql security definer set search_path = public
  as $$
  begin
    if not (select may('roles.grant')) then return false; end if;
    if not exists (select 1 from capabilities where capability = cap) then return false; end if;
    insert into capability_denials (owner_id, capability, reason, denied_by)
    values (who, cap, why, auth.uid())
    on conflict (owner_id, capability) do update set reason = excluded.reason;
    perform note_action('capability.denied', who::text, jsonb_build_object('capability', cap));
    return true;
  end
  $$;
revoke execute on function deny_capability(uuid, text, text) from public;
grant execute on function deny_capability(uuid, text, text) to authenticated;

create or replace function restore_capability(who uuid, cap text) returns boolean
  language plpgsql security definer set search_path = public
  as $$
  declare gone integer;
  begin
    if not (select may('roles.grant')) then return false; end if;
    delete from capability_denials where owner_id = who and capability = cap;
    get diagnostics gone = row_count;
    if gone > 0 then
      perform note_action('capability.restored', who::text, jsonb_build_object('capability', cap));
    end if;
    return gone > 0;
  end
  $$;
revoke execute on function restore_capability(uuid, text) from public;
grant execute on function restore_capability(uuid, text) to authenticated;

-- ── Everybody who signs up is a Game Master ─────────────────────────────────────
-- One role, granted by the database at the moment the account exists, so nothing in the app
-- has to remember to do it and no account can end up holding nothing by accident.
--
-- `security definer` because the trigger runs as whoever inserted into auth.users, which is
-- the auth service and not somebody with rights on these tables.

create or replace function grant_gm_on_signup() returns trigger
  language plpgsql security definer set search_path = public
  as $$
  begin
    insert into user_roles (owner_id, role, note)
    values (new.id, 'gm', 'granted at sign-up')
    on conflict (owner_id, role) do nothing;
    return new;
  end
  $$;
revoke execute on function grant_gm_on_signup() from public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function grant_gm_on_signup();

-- Everybody who signed up before the trigger existed. Safe to re-run.
insert into user_roles (owner_id, role, note)
select id, 'gm', 'granted at sign-up' from auth.users
on conflict (owner_id, role) do nothing;

-- ── Who there is ────────────────────────────────────────────────────────────────
-- The accounts, for the screen that hands out roles. `auth.users` is readable by no client
-- key at all, which is right, so this is the one way in and it is gated on roles.grant.
--
-- An email address is the only thing anybody can recognise an account by, and handing them
-- out is the reason this function is the most guarded read in the file. It returns nothing at
-- all rather than a row without the address: half an answer to somebody who should not be
-- asking is still an answer.
--
-- Two names, because an account has two and they answer different questions. `full_name` is
-- whatever Google or Discord said the person is called, written at sign-in and never touched
-- since. `display_name` is what they chose to publish under, and it is the one a reader of a
-- shared page sees. They are usually the same and the interesting accounts are the ones where
-- they are not, so neither is folded into the other.
--
-- The providers come from auth.identities rather than from raw_app_meta_data, because that
-- table is one row per provider and is what an account linking a second one changes.
-- `signed_in_with` is the provider on the identity used most recently, which is the answer to
-- "how did they get in last time" — auth.users.last_sign_in_at says when, and only the
-- identities say which door.
--
-- Changing what this returns needs the drop: `create or replace` cannot alter the columns of
-- a `returns table` function, and the error it raises names the return type rather than the
-- change, which is a confusing five minutes.
drop function if exists accounts(integer);
create or replace function accounts(limit_to integer default 200)
  returns table (
    id uuid,
    email text,
    created_at timestamptz,
    last_sign_in_at timestamptz,
    full_name text,
    display_name text,
    providers text[],
    signed_in_with text,
    roles text[],
    denials text[]
  )
  language sql security definer set search_path = public stable
  as $$
    select u.id,
           u.email::text,
           u.created_at,
           u.last_sign_in_at,
           -- Three keys because three providers disagree, and the same order the console
           -- reads them in: Supabase's own display_name, then the full_name / name that
           -- Google and Discord actually write. Blank is absent, so an empty string set by
           -- hand reads as no name rather than as a name nobody can see.
           nullif(
             trim(coalesce(u.raw_user_meta_data ->> 'full_name', u.raw_user_meta_data ->> 'name')),
             ''
           ) as full_name,
           nullif(trim(u.raw_user_meta_data ->> 'display_name'), '') as display_name,
           coalesce(
             (select array_agg(distinct i.provider order by i.provider)
              from auth.identities i where i.user_id = u.id),
             '{}'
           ) as providers,
           (select i.provider
            from auth.identities i
            where i.user_id = u.id
            order by i.last_sign_in_at desc nulls last, i.provider
            limit 1) as signed_in_with,
           coalesce(
             (select array_agg(r.role order by r.role) from user_roles r where r.owner_id = u.id),
             '{}'
           ) as roles,
           coalesce(
             (select array_agg(d.capability order by d.capability)
              from capability_denials d where d.owner_id = u.id),
             '{}'
           ) as denials
    from auth.users u
    where (select may('roles.grant'))
    order by u.created_at
    limit least(coalesce(limit_to, 200), 500)
  $$;
revoke execute on function accounts(integer) from public;
grant execute on function accounts(integer) to authenticated;

-- ── The first admin ─────────────────────────────────────────────────────────────
-- Bootstrapped by hand in the SQL editor, since grant_role() needs an admin to exist.
--   insert into user_roles (owner_id, role, note)
--   values ('<your auth.users id>', 'admin', 'maintainer');

-- ── What this does not touch ────────────────────────────────────────────────────
-- byline_grants stays exactly as it is. It reads like a role and is not one: it grants
-- an account the right to publish under a reserved name, and share() reports it to
-- every reader as `official`. Folding it in here would change what a stranger sees on
-- a shared page, which is a product decision rather than a schema tidy.

-- ── Checks worth doing by hand, since a definer function bypasses RLS on purpose ──
--
-- First, the trap: `auth.uid()` is null in the SQL editor. It runs as postgres with no JWT,
-- so `may()` answers false there whatever is applied, and a check written as though the
-- editor were a signed-in browser fails for a reason that has nothing to do with the schema.
--
-- Ask about an account by its id:
--   select r as role, c.capability from roles_of('<uuid>') r
--   join role_capabilities c on c.role = r order by 1, 2;
--   -- roles_of() returns setof text, so the alias is the value: `r`, never `r.role`.
--
-- Or borrow a session, which is what may() actually reads, in one transaction:
--   begin;
--   select set_config('request.jwt.claims',
--     json_build_object('sub', '<uuid>', 'role', 'authenticated')::text, true);
--   select may('roles.grant');
--   commit;
--
-- With the anon key, signed out. Every one of these must fail, and the first two are
-- the ones that catch a missing revoke:
--   select may('reports.read');      -- expect permission denied for function may
--   select * from my_capabilities(); -- expect permission denied
--   select * from user_roles;        -- expect permission denied
-- Signed in as an account holding nothing:
--   select may('reports.read');      -- expect false
--   select * from my_capabilities(); -- expect zero rows
--   select * from user_roles;        -- expect permission denied
--   select grant_role('<any uuid>', 'moderator');  -- expect false
--   select * from audit_recent();    -- expect zero rows
-- As a moderator:
--   select may('reports.read'), may('content.write');  -- expect true, false
-- As an admin:
--   select may('content.write');         -- expect true, inherited through editor
--   select * from roles_of('<own id>');  -- expect admin, moderator, editor, gm
--   select count(*) from my_capabilities();  -- expect the whole catalog
--   select revoke_role('<own id>', 'admin'); -- expect false while alone
-- And a capability the catalog does not list, which is the fail-closed case:
--   select may('nonsense');          -- expect false, for everybody including admin
--   select count(*) from capabilities;  -- expect 16 until one is added
-- That every account is a Game Master, which is worth checking after the backfill rather
-- than assuming. Roles are additive, so an admin holds `gm` too, and a missing row there is
-- invisible until the day the admin role goes: may() short-circuits for an admin either way.
--   select u.id, u.email, u.deleted_at is not null as deleted
--   from auth.users u
--   left join user_roles r on r.owner_id = u.id and r.role = 'gm'
--   where r.owner_id is null;                     -- expect no rows
--   select tgname from pg_trigger
--   where tgrelid = 'auth.users'::regclass and not tgisinternal;  -- expect on_auth_user_created
--
-- Every account is a Game Master, and one of them can be stopped from publishing:
--   select may('share.encounter');                       -- expect true, as anybody
--   select deny_capability('<uuid>', 'share.encounter', 'republished a takedown');
--   select may('share.encounter');                       -- expect false, as that account
--   select restore_capability('<uuid>', 'share.encounter');  -- expect true, then false
-- Then confirm the log cannot be forged or erased:
--   select note_action('test', 'x');            -- expect permission denied, every role
--   delete from audit_log where action = 'x';   -- expect permission denied
